# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: WildFly Galleon feature-packs for Glow - CI

on:
  pull_request:
    branches:
      - 'release'
    types: [opened, synchronize, reopened, ready_for_review]

env:
  WILDFLY_GLOW: https://github.com/wildfly/wildfly-glow/releases/download/1.0.5.Final/wildfly-glow-1.0.5.Final.zip
jobs:
  build:
    name: ${{ matrix.os }}-jdk${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: ['17', '21']

    steps:
      - uses: actions/checkout@v4
      - name: Download wildfly-glow
        run: |
          wget ${{ env.WILDFLY_GLOW }}
          unzip wildfly-glow*.zip -d .
          glowDir=$(find $PWD -type d -iname "wildfly-glow*")
          echo "WILDFLY_GLOW_DIR=$glowDir" >> "$GITHUB_ENV"
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Test
        run: |
          # Retrieve the last published WildFly release to test with
          array=(`ls -d *.Final/ *.Beta?/ | sort -n`)
          array_size=${#array[@]}
          last_index=$(( array_size-1))
          latestDir=${array[$last_index]}
          version=$(basename -a $latestDir)
          echo "Testing with WildFly version $version"
          bash tests/run-wildfly-glow-tests.sh $version
        shell: bash